import torch
import torch.nn as nn
import torch.ao.quantization as tq
import json
import os
import numpy as np
import math
import sys

# 确保当前目录可以导入 models.py
# 获取当前文件所在目录的父目录，即项目的根目录
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
# 将项目根目录添加到系统路径中
sys.path.append(parent_dir)

# 从项目根目录导入models模块
from models import make_student_model

# ================= 用户配置区域 =================
# 模型路径 (请修改为你实际的路径)
MODEL_PATH = '/work/hwc/SPARSE/distill/qat_student_runs/best_qat_int8.pt' 
# 数据路径
DATA_PATH = '/work/hwc/SPARSE/training_data/aligned_data_for_training_int/aligned_g1.json'
# 输出目录
OUT_DIR = '/work/hwc/SPARSE/infer'

# 输入数据的物理范围 (用于计算 Input Scale/ZP)
# 根据代码逻辑，patch 被归一化为 sum=1，所以范围在 [0.0, 1.0] 之间
INPUT_MIN = 0.0
INPUT_MAX = 1.0 
# ==============================================

def get_multiplier_shift(real_multiplier):
    """
    将浮点缩放因子 (Real Multiplier) 转换为定点格式:
    Real_Multiplier ~= (Quantized_Multiplier * 2^(-Shift))
    """
    if real_multiplier == 0.:
        return 0, 0
    # 使用 frexp 表示: real_multiplier = sig * 2^exp, sig in [0.5, 1)
    # 然后量化为 Q31: quantized_multiplier = round(sig * 2^31)
    # 为了使最终的缩放与 multiply_by_quantized_multiplier 中的实现对应，
    # 我们需要满足: real_multiplier == quantized_multiplier / 2^(31 + shift)
    # 代入 sig*2^exp 得到 shift = -exp
    sig, exp = math.frexp(real_multiplier)

    q_mult = int(round(sig * (1 << 31)))
    # 处理边界情况: 如果 q_mult 恰好等于 2^31，则右移一位并增加指数
    if q_mult == (1 << 31):
        q_mult >>= 1
        exp += 1

    # 根据推导，shift = -exp（shift 可以为负，表示后续会做左移）
    shift = -exp

    return q_mult, shift

def extract_layer_params(name, layer, input_scale, input_zp):
    """
    提取层的权重、偏置和量化参数
    """
    if not isinstance(layer, (nn.intrinsic.quantized.ConvReLU2d, nn.quantized.Conv2d)):
        return None, input_scale, input_zp

    # 1. 提取权重 (int8)
    # int_repr() 返回底层的 int8 数值
    weight_int8 = layer.weight().int_repr().numpy().astype(np.int8)
    
    # 2. 提取权重量化参数
    w_scale = layer.weight().q_scale()
    # PyTorch QAT 中 weight 通常是 symmetric 的，zp=0 (对于 qnnpack)
    
    # 3. 提取输出量化参数
    out_scale = layer.scale
    out_zp = int(layer.zero_point)
    
    # 4. 提取偏置 (bias)
    # Bias 在 QAT 中存储为 float，但在推理时需要转换为 int32
    # Bias_int32 = Bias_float / (Input_Scale * Weight_Scale)
    if layer.bias() is not None:
        bias_float = layer.bias().detach().numpy()
        bias_scale = input_scale * w_scale
        bias_int32 = np.round(bias_float / bias_scale).astype(np.int32)
    else:
        bias_int32 = np.zeros(weight_int8.shape[0], dtype=np.int32)
        
    # 5. 计算 Re-quantization 参数
    # Effective Scale = (Input_Scale * Weight_Scale) / Output_Scale
    effective_scale = (input_scale * w_scale) / out_scale
    multiplier, shift = get_multiplier_shift(effective_scale)
    
    print(f"Exporting {name}: InScale={input_scale:.6f}, WScale={w_scale:.6f}, OutScale={out_scale:.6f}, EffScale={effective_scale:.6f} -> Mult={multiplier}, Shift={shift}")

    return {
        'name': name,
        'weight': weight_int8,
        'bias': bias_int32,
        'multiplier': multiplier,
        'shift': shift,
        'output_zp': out_zp,
        'out_scale': out_scale,
        'in_ch': weight_int8.shape[1],
        'out_ch': weight_int8.shape[0],
        'k_h': weight_int8.shape[2],
        'k_w': weight_int8.shape[3],
        'padding': layer.padding[0]
    }, out_scale, out_zp

def write_c_header(layers_data, input_sample_data, out_dir):
    """生成 weights.h 和 input_sample.h"""
    
    # --- 1. weights.h ---
    with open(os.path.join(out_dir, 'weights.h'), 'w') as f:
        f.write("/* Generated by export_system.py */\n")
        f.write("#ifndef WEIGHTS_H\n#define WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        
        for layer in layers_data:
            name = layer['name'].upper()
            
            # 导出权重数组
            w_flat = layer['weight'].flatten()
            f.write(f"// Layer: {layer['name']} (Shape: {layer['out_ch']}x{layer['in_ch']}x{layer['k_h']}x{layer['k_w']})\n")
            f.write(f"const int8_t {name}_WEIGHTS[] = {{\n    ")
            for i, val in enumerate(w_flat):
                f.write(f"{val}, ")
                if (i+1) % 16 == 0: f.write("\n    ")
            f.write("\n};\n\n")
            
            # 导出偏置数组
            b_flat = layer['bias'].flatten()
            f.write(f"const int32_t {name}_BIAS[] = {{ {', '.join(map(str, b_flat))} }};\n\n")
            
            # 导出参数宏
            f.write(f"#define {name}_IN_CH {layer['in_ch']}\n")
            f.write(f"#define {name}_OUT_CH {layer['out_ch']}\n")
            f.write(f"#define {name}_K_H {layer['k_h']}\n")
            f.write(f"#define {name}_K_W {layer['k_w']}\n")
            f.write(f"#define {name}_PAD {layer['padding']}\n")
            f.write(f"#define {name}_MULT {layer['multiplier']}\n")
            f.write(f"#define {name}_SHIFT {layer['shift']}\n")
            f.write(f"#define {name}_OUT_ZP {layer['output_zp']}\n")
            # 导出输出 scale 以便在主程序中反量化
            f.write(f"#define {name}_OUT_SCALE {layer['out_scale']:.9f}f\n")
            f.write("-" * 40 + "\n")
            
        f.write("#endif // WEIGHTS_H\n")

    # --- 2. input_sample.h ---
    with open(os.path.join(out_dir, 'input_sample.h'), 'w') as f:
        f.write("/* Generated by export_system.py from aligned_g1.json */\n")
        f.write("#ifndef INPUT_SAMPLE_H\n#define INPUT_SAMPLE_H\n\n")
        
        patch = input_sample_data['patch']
        scale = input_sample_data['scale']
        zp = input_sample_data['zp']
        
        f.write(f"// Sample Input Parameters\n")
        f.write(f"// Raw Float Range: [{INPUT_MIN}, {INPUT_MAX}]\n")
        f.write(f"#define INPUT_SCALE {scale:.9f}f\n")
        f.write(f"#define INPUT_ZP {zp}\n")
        f.write(f"#define INPUT_IS_ODD {input_sample_data['is_odd']}\n\n")
        
        f.write(f"// Normalized Float Patch (3x5)\n")
        f.write(f"const float TEST_INPUT_FLOAT[3][5] = {{\n")
        for r in range(3):
            f.write("    { " + ", ".join([f"{x:.6f}f" for x in patch[r]]) + " },\n")
        f.write("};\n\n")
        
        # 同时也导出一个预量化好的 int8 版本供验证
        patch_int8 = np.clip(np.round(patch / scale + zp), -128, 127).astype(np.int8)
        f.write(f"// Pre-quantized Int8 Input (for debugging)\n")
        f.write(f"const int8_t TEST_INPUT_INT8[3 * 5] = {{\n    ")
        for x in patch_int8.flatten():
            f.write(f"{x}, ")
        f.write("\n};\n")
        
        f.write("#endif // INPUT_SAMPLE_H\n")

def main():
    if not os.path.exists(OUT_DIR): os.makedirs(OUT_DIR)

    # 1. 加载转换后的 Int8 模型
    print(f"Loading model from {MODEL_PATH}...")
    # 注意: 我们需要先构建模型结构，然后 convert，最后 load state_dict
    # 因为 torch.save 保存的是 convert 后的 state_dict
    
    # Step A: 创建 Float 模型结构
    model = make_student_model()
    
    # Step B: 融合模块 (必须与训练时一致)
    # models.py 中定义的 PatchNetFactory 结构: Conv -> BN -> ReLU
    # 需要手动 fuse
    # 为了安全地 fuse Conv+BN+ReLU，需要把模块置为 eval 模式
    for name in ['odd_net', 'even_net']:
        module = getattr(model, name)
        module.eval()
        # 融合列表: 索引 0,1,2 是第一层 Conv-BN-ReLU, 3,4,5 是第二层...
        fuse_list = [['net.0','net.1','net.2'], ['net.3','net.4','net.5'], ['net.6','net.7','net.8']]
        torch.quantization.fuse_modules(module, fuse_list, inplace=True)

    # 融合完成后，prepare_qat 需要模型为训练模式
    model.train()

    # Step C: 配置 QAT 参数
    model.qconfig = tq.get_default_qat_qconfig('qnnpack')
    tq.prepare_qat(model, inplace=True)
    
    # Step D: 转换为量化模型结构 (Conv2d -> QuantizedConv2d)
    model_int8 = tq.convert(model, inplace=False)
    
    # Step E: 加载权重
    try:
        state_dict = torch.load(MODEL_PATH, map_location='cpu')
        model_int8.load_state_dict(state_dict)
        print("Model weights loaded.")
    except Exception as e:
        print(f"Error loading weights: {e}")
        return

    # 2. 确定输入量化参数
    # 假设输入归一化到 [0, 1], 映射到 [-128, 127] (qnnpack use signed int8)
    # Scale = (Max - Min) / (QMax - QMin) = 1.0 / 255
    input_scale = (INPUT_MAX - INPUT_MIN) / 255.0
    input_zp = -128
    
    layers_data = []
    
    # 3. 遍历提取 'odd_net' 的层 (MCU 演示只跑一条路径，原理相同)
    # 注意: model_int8.odd_net.net 是一个 Sequential
    # 融合并 convert 后，Sequential 里的层索引可能会变，或者是 QuantizedConvReLU2d
    # 索引: 0 (Conv+BN+ReLU), 3 (Conv+BN+ReLU), 6 (Conv+BN+ReLU), 9 (Conv) -> 最后一层是纯 Conv
    
    # 提取顺序: Input -> L0 -> L1 -> L2 -> L3 (Output)
    current_scale = input_scale
    current_zp = input_zp
    
    target_indices = [0, 3, 6, 9] # 对应 models.py 中的 4 个卷积层位置
    
    print("-" * 20 + " ODD NET " + "-" * 20)
    for i, idx in enumerate(target_indices):
        layer = model_int8.odd_net.net[idx]
        layer_name = f"L{i}"
        layer_data, next_scale, next_zp = extract_layer_params(layer_name, layer, current_scale, current_zp)
        if layer_data:
            layers_data.append(layer_data)
            current_scale = next_scale
            current_zp = next_zp

    # 4. 提取测试样本
    print(f"Extracting sample from {DATA_PATH}...")
    with open(DATA_PATH, 'r') as f:
        json_data = json.load(f)
    
    # 取第一个点的数据
    first_key = list(json_data.keys())[0]
    raw_matrix = np.array(json_data[first_key]['merging']['normalized_matrix'], dtype=np.float32)
    
    # 简单的 Patch 提取逻辑 (模拟 distill_qat.py)
    # 找到最大值位置
    peak_r, peak_c = np.unravel_index(np.argmax(raw_matrix), raw_matrix.shape)
    # 提取 3x5, 假设 padding 足够或在中心
    # 这里做简单的边界保护
    r_start = max(0, peak_r - 1)
    c_start = max(0, peak_c - 2)
    patch = raw_matrix[r_start:r_start+3, c_start:c_start+5]
    
    # 如果 patch 小于 3x5 (在边缘)，需要 Pad，这里简化处理，如果尺寸不对则填0
    if patch.shape != (3, 5):
        temp = np.zeros((3, 5), dtype=np.float32)
        temp[:patch.shape[0], :patch.shape[1]] = patch
        patch = temp
        
    # 归一化 (Sum to 1)
    patch_sum = np.sum(patch)
    if patch_sum > 1e-6:
        patch = patch / patch_sum
        
    is_odd = 1 if (peak_r % 2 != 0) else 0
    
    input_sample_data = {
        'patch': patch,
        'is_odd': is_odd,
        'scale': input_scale,
        'zp': input_zp
    }
    
    # 5. 写入文件
    write_c_header(layers_data, input_sample_data, OUT_DIR)
    print(f"Done! Files generated in {OUT_DIR}")

if __name__ == "__main__":
    main()