/* Generated by export_system.py from aligned_g1.json */
#ifndef INPUT_SAMPLE_H
#define INPUT_SAMPLE_H

// Sample Input Parameters
// Raw Float Range: [0.0, 1.0]
#define INPUT_SCALE 0.003921569f
#define INPUT_ZP -128
#define INPUT_IS_ODD 0

// Normalized Float Patch (3x5)
extern const float TEST_INPUT_FLOAT[3][5];

// Pre-quantized Int8 Input (for debugging)
extern const int8_t TEST_INPUT_INT8[3 * 5];
#endif // INPUT_SAMPLE_H
