#include "model_meta.h" // Include meta for completeness (though not strictly needed here)
#include "weights.h"    // Include the header declaring these variables

// This file defines the actual constant arrays for weights, biases,
// and requantization parameters generated by the export script.

// --- Block 1 Depthwise Convolution ---
const int8_t g_block1_dw_weight[18] = {
  50, 72, -128, -66, 4, 1, 53, 68, -19, -71, -73, -28, -54, -41, -31, -63, 127, 66
};
const int32_t g_block1_dw_bias[2] = { // Bias is typically int32 after scaling
  0, 0
};
const int32_t g_block1_dw_multiplier[2] = { // Per-channel multiplier for requantization
  1301118827, 1093899272
};
const int32_t g_block1_dw_shift[2] = { // Per-channel shift for requantization
  38, 38
};

// --- Block 1 Pointwise Convolution (Fused ReLU) ---
const int8_t g_block1_pw_weight[8] = {
  -128, -70, 105, 127, -34, 127, -112, 127
};
const int32_t g_block1_pw_bias[4] = {
  -882, 2461, 2192, 2616
};
const int32_t g_block1_pw_multiplier[4] = {
  1930333631, 1963589686, 1452107832, 1734448939
};
const int32_t g_block1_pw_shift[4] = {
  37, 37, 36, 37
};

// --- Block 2 Depthwise Convolution ---
const int8_t g_block2_dw_weight[36] = {
  45, -80, -65, -3, -128, 81, -34, 40, -92, 23, -90, 68, 8, 4, -14, -45, 28, -128,
  -127, -92, 82, 41, -33, -6, -13, 99, -33, 55, 119, -89, -3, -22, -114, -124, 12,
  62
};
const int32_t g_block2_dw_bias[4] = {
  0, 0, 0, 0
};
const int32_t g_block2_dw_multiplier[4] = {
  1195421639, 1552165612, 1146844958, 1622996875
};
const int32_t g_block2_dw_shift[4] = {
  38, 38, 38, 39
};

// --- Block 2 Pointwise Convolution (Fused ReLU) ---
const int8_t g_block2_pw_weight[16] = {
  -126, 55, 87, -12, 33, 23, 127, 95, -104, -44, 52, 127, 109, 127, 24, -82
};
const int32_t g_block2_pw_bias[4] = {
  -599, 2588, -1155, 2739
};
const int32_t g_block2_pw_multiplier[4] = {
  1488153788, 1970083679, 1362767731, 1455319091
};
const int32_t g_block2_pw_shift[4] = {
  36, 36, 36, 36
};

// --- Head Linear Layer 0 (Fused ReLU) ---
const int8_t g_head_0_weight[48] = {
  17, -41, -94, 127, 107, -95, 0, 0, 0, 0, 0, 0, 79, 104, 127, 86, -92, -45, 75,
  15, -44, -53, 127, 123, 0, 0, 0, 0, 0, 0, 18, 44, -21, 93, -43, 127, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0
};
const int32_t g_head_0_bias[8] = {
  1714, 0, -1613, -18218, 0, 11068, 0, 0
};
const int32_t g_head_0_multiplier[8] = {
  1640207347, 1270781358, 1686373591, 2137193972, 2070970910, 1934164409,
  2070970910, 2070970910
};
const int32_t g_head_0_shift[8] = {
  39, 53, 39, 39, 54, 39, 54, 54
};

// --- Head Linear Layer 2 ---
const int8_t g_head_2_weight[16] = {
  62, 0, 39, -125, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
const int32_t g_head_2_bias[2] = {
  -15993, 0
};
const int32_t g_head_2_multiplier[2] = {
  1592814887, 1936446847
};
const int32_t g_head_2_shift[2] = {
  36, 51
};

// --- GAP Requantization Parameters ---
// NOTE: Not used by the current GAP op, but kept for completeness matching export.
const int32_t g_gap_out_multiplier[1] = {
  1472230947
};
const int32_t g_gap_out_shift[1] = {
  33
};
